services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
       test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
       interval: 10s
       timeout: 5s
       retries: 3
    networks:
      - ecommerce-network

  app:
    build:
      context: .
    container_name: java_app_container
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/main/resources/templates:/app/templates
      - ./src/main/resources/static:/app/static
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge